name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      continue-on-error: true

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test_containter:$(date +%s)
